### PR TITLE
ja-po: Add Japanese translations

### PR DESCRIPTION
**Pull request by narusemotoki**
I have translated to git clone.

### CODE REVIEW

**Comment by modocache** [comment]
Awesome, thanks for the help! Also, I created a small Wiki page with notes on translation, check it out at: https://github.com/modocache/git-po-ja/wiki/Japanese-Translation-Notes

**Comment by narusemotoki** [comment]
I was able to gain self-confidence with this.
`I think our #1 priority should be to translate all the strings. We can worry about the quality of the translations later.`

Thank you.

**Comment by modocache** [comment]
Haha, great! To be honest, I was mainly referring to my own poor translations! :sweat_smile: 

There are also inconsistencies in some of our translations, such as using "使うことができません" or "使えません” or "使用できません". I don't think it's important to fix these just yet, though. Once we've translated all the strings we can work on improving them.

The number one priority should be to get these translations to users. People who find them unnatural may submit patches or send suggestions, thereby making the work a little easier for us! After all, it's easier to correct unnatural Japanese than it is to translate from English.

**Comment by narusemotoki** [comment]
I think your Japanese translation is very good. :+1: You have a sense of Japanese language than me. In fact, when my translations conflict with your translations, I gave priority to some your translations.
I'm grateful that you gave me the opportunity of this interesting translation. :laughing:

**Pull request merged**
